language: node_js

node_js:
- "8"

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test

after_success:
  - npm run pack

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "knaydenov-material-grid-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "knaydenov@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true